package com.sample
 
import com.sample.DroolsMessage;
import com.sample.DroolsTimer;
import com.sample.DroolsUtilities;
 
rule "SendeMail"
	when
		DroolsCustomer (emailAddress != null , address : emailAddress )
		DroolsMessage( FlowStatus == DroolsMessage.EMAIL)
	then
    	DroolsUtilities du = new DroolsUtilities();
    	du.sendEmail(address);
        DroolsTimer t = new DroolsTimer();
        t.setLength(10000);
        t.pause();
end